<?php
/**
 * Footer About
 *
 * @category    design
 * @package     core_template
 *
 * @author      Oleksandr Kostynian
 */
?>

<div class="footer_about">
    <h3 id="about_us">About Us</h3>
    <p> Urban Decay is beauty with an edge.
        Feminine, dangerous and fun, it appeals to women who relish their individuality and dare to express it.
        From our insane range of velvety Eyeshadows—including the bestselling (and often-copied)
        Naked Palettes—to our award-winning eye liners, budge-proof mascaras and legendary Makeup Setting Sprays,
        we've been shaking up the industry for over 15 years.
        <a href="<?php echo $this->getUrl('about-urbandecay');?>" rel="nofollow" title="Read more">More</a>
    </p>
    <div class="footer_bottom_logos_wrapper">
        <a href="#">
            <div class="bt_logo" id="footer_bottom_logo1"></div>
            <div class="bt_logo" id="footer_bottom_logo2"></div>
            <div class="bt_logo" id="footer_bottom_logo3"></div>
            <div class="bt_logo" id="footer_bottom_logo4"></div>
        </a>
    </div>
</div>