<?php
/**
 * Content items in homepage
 *
 * @category    design
 * @package     core_template
 *
 * @author      Oleksandr Kostynian
 */


if(Mage::getSingleton('cms/page')->getIdentifier() == 'home' and Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms') {


?>

<div class="inner"><a href="#"> <img class="block_bacground" src="<?php echo $this->getSkinUrl('images/001.jpg') ?>"
                                     alt="Too Much Vice Is Never Enough. 20 All-New Shades. Slimmer Case.
                                     Matching Bag.  Get It Now &gt;" /> </a></div>
<div class="content_medium_items">
    <div class="medium_item">
        <div class="medium_image"><a href="#"> <img src="<?php echo $this->getSkinUrl('images/G1_Locked_v2.jpg') ?>" alt="" /> </a></div>
        <div class="medium_text">
            <h2>Locked offer</h2>
            <p>Unlock an exclusive offer. Create an account<br />or log in now.</p>
            <a class="button" href="#">create account / sign in</a></div>
    </div>
</div>
<div class="content_medium_items">
    <div class="medium_item">
        <div class="medium_image"><a href="#"> <img src="<?php echo $this->getSkinUrl('images/SonaVideo_G123_081914.jpg') ?>" alt="" /> </a></div>
        <div class="medium_text">
            <h2>Video</h2>
            <p>Watch MakeupBySona do a smoky eye with Naked2 Basics.</p>
            <a class="button" href="#">view now</a></div>
    </div>
</div>
<div class="content_medium_items">
    <div class="medium_item">
        <div class="medium_image"><a href="#"> <img src="<?php echo $this->getSkinUrl('images/G3_EmailSignup.jpg') ?>" alt="" /> </a></div>
        <div class="medium_text">
            <h2>Email Sign Up</h2>
            <p>Get notified first about new products, exclusive offers<br /> and more!</p>
            <a class="button" href="#">sign up now</a></div>
    </div>
</div>
<?php }