<?php
/**
 * Product View Social
 *
 * @category    design
 * @package     core_template
 *
 * @author      Illya Dzherelyuk
 */
?>
<div class="product_view_social_wrapper">
    <div class="product_social_pinterest">
        <div class="pinterest_icon">
            <a href="https://www.pinterest.com/" target="_blank"></a>
        </div>
    </div>
    <div class="product_social_facebook">
        <div class="facebook_icon">
            <a href="https://www.facebook.com/" target="_blank"></a>
        </div>
    </div>
</div>