<?php
/**
 *
 * LOGIN FORM
 *
 * @category    design
 * @package     base_default
 * @author      Oleksandr Kostynian
 */
?>

<div class="account-login">
    <div class="primary">
    <div class="b-myaccount-header">
        <h1><?php echo $this->__('Account Sign In') ?></h1>
    </div>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>

        <div class="col2-set">
            <div class="col-1">
                <div class="login_page">
                    <ul class="form-list">
                        <li>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" placeholder="Email" maxlength="50" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password"  placeholder="Password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                </div>
                <button type="submit" class="button-color" title="<?php echo $this->__('Login') ?>" value="Sign In" name="send" id="send2">
                    <span><?php echo $this->__('Sign in') ?></span>
                </button>
                <div class="fogot-pass-link-wrapper">
                  <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                </div>
            </div>
            <div class="col-2">
                <div class="create-account-benefits">
                    <h2>DON'T HAVE AN ACCOUNT?</h2>
                    <p>Registering for an account will give you access to all the great features on UrbanDecay.com, including:</p>
                    <ul>
                        <li>Notifications about new products</li>
                        <li>Deluxe samples</li>
                        <li>Exclusive offers</li>
                        <li>Access to your order history</li>
                        <li>The ability to save your favorites</li>
                        <li>Expedited checkout and more!</li>
                    </ul>
                </div>
                <a href="#" class="button-color"
                   onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"
                   title="Creating an account is easy. Just fill in the form below and enjoy the benefits of having an account1.">
                    <span>Create Account</span>
                </a>
            </div>
        </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
    </div>
</div>
