<?php
/**
 *
 * LOGIN FORM
 *
 * @category    design
 * @package     base_default
 * @author      Oleksandr Kostynian
 */
?>

<div class="account-login">
    <div class="primary">
    <div class="b-myaccount-header">
        <h1><?php echo $this->__('Account Sign In') ?></h1>
    </div>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>

        <div class="col2-set">
            <div class="col-1">
                <div class="login_page">
                    <ul class="form-list">
                        <li>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="log-in-form-input required-entry validate-email" placeholder="Email" maxlength="50" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="log-in-form-input required-entry validate-password"  placeholder="Password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                </div>
                <button type="submit" class="button-color" title="<?php echo $this->__('Login') ?>" value="Sign In" name="send" id="send2">
                    <span><?php echo $this->__('Sign in') ?></span>
                </button>
                <div class="fogot-pass-link-wrapper">
                  <a href="#" onclick="div_show()" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                </div>
            </div>
            <div class="col-2">
                <div class="create-account-benefits">
                    <h2><?php echo $this->__('DON\'T HAVE AN ACCOUNT?') ?> </h2>
                    <p><?php echo $this->__('Registering for an account will give you access to all the great features on UrbanDecay.com, including:') ?> </p>
                    <ul>
                        <li><?php echo $this->__('Notifications about new products') ?> </li>
                        <li><?php echo $this->__('Deluxe samples') ?> </li>
                        <li><?php echo $this->__('Exclusive offers') ?></li>
                        <li><?php echo $this->__('Access to your order history') ?></li>
                        <li><?php echo $this->__('The ability to save your favorites') ?></li>
                        <li><?php echo $this->__('Expedited checkout and more!') ?></li>
                    </ul>
                </div>
                <a href="#" class="button-color"
                   onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"
                   title="Creating an account is easy. Just fill in the form below and enjoy the benefits of having an account1.">
                    <span><?php echo $this->__('Create Account') ?></span>
                </a>
            </div>
        </div>

        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
    </div>

<div id="popup"></div>
<div id="popupContent">
    <!-- Contact Us Form -->
    <div class="forgotpass-wrapper">
        <a href="#" onclick ="div_hide()">
            <div class="close-popup-wrapper">
                <div class="close-popup">
                    &times;
                </div>
            </div>
        </a>
        <div class="request_password_page">
            <h1>
                <?php echo $this->__('Forgot password') ?>
            </h1>

            <p class="message"> <?php echo $this->__('Give us the email address you use to log in to Urban Decay and we\'ll send you instructions for resetting your password.') ?></p>
            <p class="b-request_password-signature"><?php echo $this->__('Thanks, ') ?><br><span><?php echo $this->__('Team UD') ?></span></p>
            <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" tabindex="1" method="post" id="form-validate" name="dwfrm_requestpassword">
                <fieldset>
                    <div class="f_field f_field_email" data-required-text="Please enter your email address">
                        <input type="text" name="email" alt="email" id="email_address"  class="textinput f_email   required" placeholder="Email" maxlength="50" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>">
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </div>
                    <div class="formfield formfield_button">
                        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button submit_button" value="Submit" name="dwfrm_requestpassword_send">
                            <?php echo $this->__('Submit')?>
                        </button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>
<div class="b-customer_service-assets">
<div class="bottom-banners">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customer_service_bottom')->toHtml(); ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('live_chat_bottom')->toHtml(); ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faqs_bottom')->toHtml(); ?>
</div>
</div>


