<div class="social-sign-in">
    <a href="#">
    <div class="google-plus social-ico"></div>
    </a>
    <a href="#">
    <div class="facebook social-ico"></div>
    </a>
    <a href="#">
    <div class="twitter social-ico"></div>
    </a>
    <a href="#">
    <div class="social-p social-ico"></div>
    </a>
    <a href="#">
    <div class="instagram social-ico"></div>
    </a>
</div>
<div class="sep-wrapper">
    <div class="sep"></div>
    <span>or</span>
    <div class="sep"></div>
</div>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
    <?php echo $this->getBlockHtml('formkey'); ?>
            <div class="login_page">
                <ul class="form-list">
                    <li>
                        <div class="input-box">
                            <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="log-in-form-input required-entry validate-email" placeholder="Email" maxlength="50" title="<?php echo $this->__('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                        <div class="input-box">
                            <input type="password" name="login[password]" class="log-in-form-input required-entry validate-password"  placeholder="Password" id="pass" title="<?php echo $this->__('Password') ?>" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                </ul>
                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            </div>
            <button type="submit" class="button-color" title="<?php echo $this->__('Login') ?>" value="Sign In" name="send" id="send2">
                <span><?php echo $this->__('Sign in') ?></span>
            </button>
            <div class="fogot-pass-link-wrapper">
                <a href="#" onclick="div_show()" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
            </div>
    <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
        <input name="context" type="hidden" value="checkout" />
    <?php endif; ?>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('login-form', true);
    //]]>
</script>
