<?php
/**
 *
 * LOGIN FORM
 *
 * @category    design
 * @package     base_default
 * @author      Oleksandr Kostynian
 */
?>

<div class="account-login">
    <div class="primary">
    <div class="b-myaccount-header">
        <h1><?php echo $this->__('Account Sign In') ?></h1>
    </div>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>

        <div class="col2-set">
            <div class="col-1">
                <div class="login_page">
                    <ul class="form-list">
                        <li>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="log-in-form-input required-entry validate-email" placeholder="Email" maxlength="50" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="log-in-form-input required-entry validate-password"  placeholder="Password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                </div>
                <button type="submit" class="button-color" title="<?php echo $this->__('Login') ?>" value="Sign In" name="send" id="send2">
                    <span><?php echo $this->__('Sign in') ?></span>
                </button>
                <div class="fogot-pass-link-wrapper">
                  <a href="#" onclick="div_show()" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                </div>
            </div>
            <div class="col-2">
                <div class="create-account-benefits">
                    <h2>DON'T HAVE AN ACCOUNT?</h2>
                    <p>Registering for an account will give you access to all the great features on UrbanDecay.com, including:</p>
                    <ul>
                        <li>Notifications about new products</li>
                        <li>Deluxe samples</li>
                        <li>Exclusive offers</li>
                        <li>Access to your order history</li>
                        <li>The ability to save your favorites</li>
                        <li>Expedited checkout and more!</li>
                    </ul>
                </div>
                <a href="#" class="button-color"
                   onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"
                   title="Creating an account is easy. Just fill in the form below and enjoy the benefits of having an account1.">
                    <span>Create Account</span>
                </a>
            </div>
        </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
    </div>

<div id="popup"></div>
<div id="popupContent">
    <!-- Contact Us Form -->
    <div class="forgotpass-wrapper">
        <a href="#" onclick ="div_hide()">
            <div class="close-popup-wrapper">
                <div class="close-popup">
                    &times;
                </div>
            </div>
        </a>
        <div class="request_password_page">
            <h1>
                Forgot password
            </h1>
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            <p class="message">Give us the email address you use to log in to Urban Decay and we'll send you instructions for resetting your password.</p>
            <p class="b-request_password-signature">Thanks, <br><span>Team UD</span></p>
            <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" tabindex="1" method="post" id="form-validate" name="dwfrm_requestpassword">
                <fieldset>
                    <div class="f_field f_field_email" data-required-text="Please enter your email address">
                        <input type="text" name="email" alt="email" id="email_address"  class="textinput f_email   required" placeholder="Email" maxlength="50" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>">
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                    </div>
                    <div class="formfield formfield_button">
                        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button submit_button" value="Submit" name="dwfrm_requestpassword_send">
                            Submit
                        </button>
                    </div>
                    <input type="hidden" name="dwfrm_requestpassword_securekey" value="398748497">
                </fieldset>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>


<div class="b-customer_service-assets">
    <div class="b-customer_service-item">
        <div class=" content_asset">
            <div class="b-widget">
                <h3 class="b-widget-title">Customer Service</h3>
                <p class="b-widget-info">Got questions? We've got answers!</p>
                <ul class="b-widget-list">
                    <li class="b-widget-list_item"><a href="tel:+18007848722">1.800.784.8722</a></li>
                </ul>
                <p class="b-widget-info">Mon - Fri: 7am - 5pm, PST (Excluding holidays)</p>
            </div>
        </div>
    </div>
    <div class="b-customer_service-item">
        <div class=" content_asset">
            <div class="b-widget">
                <h3 class="b-widget-title">Live Chat</h3>
                <p class="b-widget-info">Our Beauty Advisors are ready to answer your questions.</p>
                <ul class="b-widget-list">
                    <li id="lpchatbuttondiv" class="b-widget-list_item" style="visibility: visible;"><a href="#" class="'b-widget-list_link'" onclick="lpMTagConfig.dynButton0.actionHook();"> </a></li>
                </ul>
                <p class="b-widget-info">Mon - Fri: 7am - 4pm, PST (Excluding holidays)</p>
            </div>
        </div>
    </div>
    <div class="b-customer_service-item">
        <div class="content_asset">
            <div class="b-widget">
                <h3 class="b-widget-title">FAQs</h3>
                <p class="b-widget-info">Check out our <a href="https://www.urbandecay.com/faq">FAQ section</a> to see if we’ve covered your question.</p>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>


