<?php
/**
 * Product View Social
 *
 * @category    design
 * @package     core_template
 *
 * @author      Illya Dzherelyuk
 */
?>
<?php
$products = Mage::getSingleton('Mage_Reports_Block_Product_Viewed')->getItemsCollection()
    ->setPageSize(4)
    ->setCurPage(1);
?>

<div class="recently-viewed">
    <ul class="products-grid">
        <?php foreach ($products as $product)  : ?>
            <li class="item">
                <a class="product-image" href="<?php echo $product->getProductUrl()?>">
                    <img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image')
                        ->constrainOnly(false)
                        ->keepAspectRatio(true)
                        ->keepFrame(true)
                        ->keepTransparency(true)
                        ->backgroundColor(array(255,255,255))
                        ->resize(135, 135); ?>" alt="">
                </a>
                <h2 class="product-name"><a href="<?php echo $product->getProductUrl()?>"><?php echo $product->getName()?></a></h2>

                <?php
                $storeId = Mage::app()->getStore()->getId();
                $summaryData = Mage::getModel('review/review_summary')
                    ->setStoreId($storeId)
                    ->load($product->getId());

                if ($summaryData['rating_summary']): ?>
                    <div class="ratings">
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo $summaryData['rating_summary']; ?>%"></div>
                        </div>
                    </div>
                <?php endif; ?>

                <div class="price-box">
                    <span class="regular-price">
                        <?php echo Mage::app()->getStore()->getCurrentCurrency()->format($product->getFinalPrice());?>
                    </span>
                </div>
                <div class="actions">
                    <button type="button" title="Shop Now" class="button btn-cart" onclick="setLocation('<?php echo $product->getProductUrl()?>')"><span><?php echo $this->__('Shop now') ?></span></button>
                </div>
            </li>
        <?php
        endforeach; ?>
    </ul>
</div>