<?php
/**
* Footer
*
* @category    design
* @package     base_default
* @author      Oleksandr Kostynian
*/
/**
* @var Mage_Page_Block_Html_Footer $this
*/
?>

<div class="footer-container">
    <div class="footer_top_wrapper">
        <?php echo $this->getChildHtml('social') ?>
        <?php echo $this->getChildHtml('subscribe') ?>
        <div class="clear"></div>
    </div>
    <div class="footer">
        <?php echo $this->getChildHtml('footer_about') ?>
        <div class="footer_links">
            <?php echo $this->getChildHtml('footer_links') ?>
            <div class="copyright">
                <address><?php echo $this->getCopyright() ?></address>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
