<?php
/**
* Footer
*
* @category    design
* @package     base_default
* @author      Oleksandr Kostynian
*/
/**
* @var Mage_Page_Block_Html_Footer $this
*/
?>

<div class="footer-container">
    <div class="footer_top_wrapper">
        <div class="footer_top">
        <?php echo $this->getChildHtml('subscribe') ?>
            <div class="social_footer">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_social')->toHtml(); ?>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="footer">
        <div class="footer_about">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('about_us_footer')->toHtml(); ?>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_logos')->toHtml(); ?>
        </div>
        <div class="footer_links">
            <div class="footer_links_first">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_first')->toHtml(); ?>
            </div>
            <div class="footer_links_second">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_second')->toHtml(); ?>
            </div>
            <div class="clear"></div>
            <div class="copyright">
                <address><?php echo $this->getCopyright() ?></address>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
