<?php
/**
 *
 *
 *
 *
 *
 * @category    design
 * @package     base_default
 *
 */
?>
<ul class="top-links">
    <li>
        <?php if (! Mage::getSingleton('customer/session')->isLoggedIn()): ?>
            <div class="header-sign-in-wrapper">
            <a class="login" href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>" title="Sign in / Register"><?php echo $this->__('Sign in / Register') ?> </a>
            <div class="header-sign-in-div">
                <div class="header-sign-in">
                    <div class="top-arrow"></div>
                    <?php echo $this->getChildHtml('sign_in_mini_form') ?>
                </div>
            </div>
            </div>
        <?php else: ?>
            <?php
                $customer = Mage::getSingleton('customer/session')->getCustomer();
                $name = $customer->getFirstname();
                if ($customer->getAvatarSrc()) {
                    $avatar = '<img class="customer-mini-avatar" src="'. Mage::getBaseUrl('media').'avatar/' . $customer->getAvatarSrc() . '" width="28" />';
                    echo $avatar;
                }
                else {
                    $avatar = '<img class="customer-mini-avatar" src="'. $this->getSkinUrl('images/avatar') . '/avatar.png' . '" width="28" />';
                    echo $avatar;
                }
            ?>
            <span><?php echo $this->__('Hi, ') ?></span>
            <a class="customer-page-link" href="<?php echo Mage::getUrl('customer/account/edit'); ?>" title="Account"><?php echo $name; ?></a>
            <a class="login" href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>" title="Sign Out"><?php echo $this->__('Sign Out') ?> </a>
        <?php endif; ?>
    </li>
    <li class="header-cart-link">
        <a class="cart_link" href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>" title="View Cart">
            <div class="header-bag-wrapper">
                <div class="header-bag-img"></div>
                <span class="mini_cart_label"><?php echo $this->__('My Bag') ?> </span>
                <span class="mini_cart_quantity" id="<?php echo Mage::helper('checkout/cart')->getItemsCount(); ?>">(<?php echo Mage::helper('checkout/cart')->getItemsCount(); ?>)</span>
            </div>
        </a>
        <?php
        $request = $this->getRequest();
        $module = $request->getModuleName();
        $controller = $request->getControllerName();
        $action = $request->getActionName();
        if($module == 'checkout' && $controller == 'cart' && $action == 'index')
        {

            //if Cart Page Block not displaying

        } else {
        if (Mage::helper('checkout/cart')->getItemsCount() > 0) { ?>
        <div class="header-cart-mini-div-wrapper">
            <div class="top-arrow"></div>
            <div class="mini-cart">
                <div class="mini_cart_header_wrapper">
                    <span class="mini_cart_title"><?php echo $this->__('My Bag') ?> </span>
                    <span class="mini_cart_title">(<?php echo Mage::helper('checkout/cart')->getItemsCount(); ?>)</span>
                </div>
                <div class="mini-cart-items-in-bag-wrapper">
                    <?php echo $this->getChildHtml('mini_cart_div'); ?>
                </div>
            </div>

            <div class="mini-cart-right-items-wrapper">
                <div class="mini_cart_title_right">
                    <?php echo $this->__('We Know You\'ll Love') ?>
                </div>
                <?php echo $this->getChildHtml('right_four_items') ?>
            </div>

            <div class="mini-cart-button-wrapper">
               <div class="mini-cart-subtotal">
               <?php
                    echo $this->__('Subtotal: ');
                    $totals = Mage::getSingleton('checkout/cart')->getQuote()->getTotals();
                    $totals = $totals["subtotal"]->getValue();
                    echo Mage::helper('core')->currency($totals, true, false);
               ?>
               </div>
                <a class="mini_cart_link_cart" href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>" title="View Cart">
                    <span> <?php echo $this->__('Checkout') ?> </span>
                </a>
            </div>
        </div>
            <?php } else { ?>
            <div class="mini-cart-empty">
                <div class="top-arrow"></div>
                <?php echo $this->__('Your bag is currently empty. START SHOPPING!') ?>
            </div>
            <?php }} ?>

    </li>
</ul>

<script type="text/javascript">
    //<![CDATA[
    $j(document).ready(function(){
        var $numItems = $j('.mini_cart_quantity').attr('id');
            if ( $numItems > 0) {
                $j('.header-bag-wrapper').addClass('items-in-bag');
            }
    });
    //]]>
</script>
