
<div class="cart-wrapper">
<div class="page-title">
    <h1><?php echo $this->__('SHOPPING BAG') ?></h1>
</div>
<div class="cart-empty">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
    <p><?php echo $this->__('Your shopping bag is empty. ') ?></p>
    <p><?php echo $this->__('<a href="%s">Shop now</a> to find your favorite products.', $this->getContinueShoppingUrl()) ?></p>
    <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
</div>
</div>