<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
$package = Mage::getDesign()->getPackageName();
$theme = Mage::getDesign()->getTheme('frontend');
?>
<div class="opc-wrapper-opc design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">

    <div class="l-back_to_bag">
        <a class="b-back_to_bag" href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>">
            Back to Shopping Bag
        </a>
    </div>
    <div class="l-checkout-head">
        <h2 class="b-checkout-title"><?php echo $this->__('Checkout')?></h2>
        <span class="b-checkout-message"><?php echo $this->__('All fields are required unless marked optional.')?></span>
    </div>

	<div class="clear"></div>
    <div class="checkout-main_section">
        <div class="opc-col-left">
            <form id="opc-address-form-billing" method="post">
                <?php echo $this->getChildHtml('billing')?>
            </form>

            <?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
                <div class="shipping-block">
                    <h3><?php echo $this->__('Shipping Method')?></h3>
                    <div id="shipping-block-methods">
                        <?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
                    </div>
                </div>
            <?php endif;?>
        </div>

        <div class="opc-col-center">
            <legend>
                <h3><?php echo $this->__('Shipping')?></h3>
            </legend>
            <form id="opc-address-form-shipping" class="hidden" method="post">
                <?php echo $this->getChildHtml('shipping')?>
            </form>

		<?php if(Mage::helper('opc')->isShowComment()):?>
			<?php echo $this->getChildhtml('customer.comment');?>
		<?php endif;?>

            <div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>">
                <legend>
                    <h3><?php echo $this->__('Payment')?></h3>
                </legend>

                <div class="discount-block">
                    <div class="f_legend">
                        <span class="f_legend_value"><?php echo $this->__('E-Gift Card')?></span>
                    </div>
                    <?php echo $this->getChildhtml('coupon');?>
                </div>

                <?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
            </div>

            <?php if(Mage::helper('opc')->isShowComment()):?>
                <?php echo $this->getChildhtml('customer.comment');?>
            <?php endif;?>

        </div>
    </div>

    <div class="opc-col-right">
        <div id="opc-review-block">
		<?php echo $this->_getReviewHtml()?>
		</div>
        <div class="checkout_cart_actions">
            <div class="checkout_divider">or</div>
            <div class="paypal-checkout">
                <a href="#">
                    <img src=<?php echo $this->getSkinUrl('images/paypal.png') ?>>
                </a>
            </div>
        </div>
    </div>
</div>
<script>
	var vopc = '<?php echo Mage::getConfig()->getModuleConfig("IWD_Opc")->version;?>';
	IWD.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	IWD.OPC.Checkout.isVirtual = true;
	<?php endif;?>	 
</script>

<div class="opc-ajax-loader">
	<div id="floatingCirclesG">
		<div class="f_circleG" id="frotateG_01"></div>
		<div class="f_circleG" id="frotateG_02"></div>
		<div class="f_circleG" id="frotateG_03"></div>
		<div class="f_circleG" id="frotateG_04"></div>
		<div class="f_circleG" id="frotateG_05"></div>
		<div class="f_circleG" id="frotateG_06"></div>
		<div class="f_circleG" id="frotateG_07"></div>
		<div class="f_circleG" id="frotateG_08"></div>
	</div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	
	<div class="opc-messages">
		<a class="close-message-wrapper"></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>

<div class="b-customer_service-assets">
    <div class="bottom-banners">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customer_service_bottom')->toHtml(); ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('live_chat_bottom')->toHtml(); ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faqs_bottom')->toHtml(); ?>
    </div>
</div>